### ISSUE TITLE
Error, can't connect to gate

### ISSUE THREAD

**Issue by bluewidy** [JKornev/hidden#12]
![default](https://user-images.githubusercontent.com/40682277/51798615-d8b94e00-2258-11e9-8469-e921a5071fe7.PNG)

Hello. I am a regular computer user. I am not a programmer. The reason for the above problem is that Seems like I did not load the driver into the kernel.

I would appreciate it if you could teach me how to load the driver into the kernel.

**Comment by bluewidy** [comment]
I have solved the above problem now! The cause of the problem was that I did not load the driver, and I solved the problem by loading the driver with the command "sc start hidden".

**Comment by JKornev** [comment]
Ok good, in any case I'll add instructions to a project description

**Comment by MisterChangRay** [comment]
maybe you should write a start guide.   how to load  load the driver to the kernel in windows7;

**Comment by JKornev** [comment]
Hi,

Yup you're 100% right and I gonna do it soon. The only problem is time.
