### ISSUE TITLE
PsGetThreadProcessId  in ProcessPreCallback

### ISSUE THREAD

**Issue by hsheep** [JKornev/hidden#13]
hi, Is it correct to use PsGetThreadProcessId  in ProcessPreCallback ?

`OB_PREOP_CALLBACK_STATUS ProcessPreCallback(PVOID RegistrationContext, POB_PRE_OPERATION_INFORMATION OperationInformation)
{
	LogInfo("Allow protected process access from %d to %d", (ULONG)PsGetCurrentProcessId(), (ULONG)**PsGetThreadProcessId**(OperationInformation->Object));

}`

**Comment by JKornev** [comment]
Hi,

Yup seems like a bug. Fixed as part of 8e4dd9556228a9f9657ff5bb2f7349b2ebe0e286

Thanks!
