### ISSUE TITLE
RegPostEnumValue  preinformation

### ISSUE THREAD

**Issue by hsheep** [JKornev/hidden#14]
hi Jora Kornev:
Why does RegPostEnumKey preInfo use PREG_ENUMERATE_KEY_INFORMATION struct, 
and RegPostEnumValue's preInfo also uses PREG_ENUMERATE_KEY_INFORMATION ,
MSDN show me REG_ENUMERATE_VALUE_KEY_INFORMATION.

**Comment by JKornev** [comment]
Hi,

Thanks for the report, seems like a bug, will solve it today.

**Comment by JKornev** [comment]
Solved
