### ISSUE TITLE
how to hide service?

### ISSUE THREAD

**Issue by spider146** [JKornev/hidden#16]

**Comment by JKornev** [comment]
Hi,

Currently you are able to hide only service registry stuff and its files. But in this case service still can be detected via Service Control Management API. I solved this but haven't published a technology yet. The component that is able to hide services from SCM will be published soon as part of the following repo:
https://github.com/JKornev/scex Can't say an exact ETA but it will be published soon 100%, and after it i'm going to port this rootkit technique to this Hidden driver.

**Comment by spider146** [comment]
@JKornev looking forward

**Comment by sobuj53** [comment]
@JKornev This will be the cherry on top. Looking forward to your push.
