### ISSUE TITLE
ignore pid does not work

### ISSUE THREAD

**Issue by goraegori** [JKornev/hidden#18]
I think it's kinda bug.
![image](https://user-images.githubusercontent.com/39221443/68924121-5a1ba600-07c3-11ea-8229-083a9eac1e89.png)

+ I am using release- v1.0

**Comment by JKornev** [comment]
Hi,

Thanks for report. What is your OS version?

Regards,
Nikita K.

**Comment by goraegori** [comment]
I am using W10x64
thanks for fast response

**Comment by JKornev** [comment]
Hi,

I found out that it's a bug, so I fixed it in the code by the following commit a8dc93e7b587eb65efb8417772858a7c6eea829c

So you can pull the latest changes and it should work now.
