### ISSUE TITLE
how to hide port

### ISSUE THREAD

**Issue by b1ueb0y** [JKornev/hidden#19]
hi bro,how to hide tcp/udp port,could you give me some suggestions?thanks!

**Comment by JKornev** [comment]
Hi,

What do you mean by hiding a port? Hide a network port for specific applications?

Regards,
JKornev

**Comment by JKornev** [comment]
So there is no such feature and it's not clear what do you mean, closed

**Comment by b1ueb0y** [comment]
> Hide a network port for specific applications

Hide a network port for cmd.exe execute "netstat -ant"
