### ISSUE TITLE
Error, can't connect to gate

### ISSUE THREAD

**Issue by BotnUm** [JKornev/hidden#20]
when i run hiddencli.exe, it show this error.

**Comment by JKornev** [comment]
Hi,

Which error? Please provide screen or console output.

**Comment by BotnUm** [comment]
Console said Error, can't connect to gate.

2019년 12월 16일 (월) 04:33, Jora Kornev <notifications@github.com>님이 작성:

**Comment by JKornev** [comment]
To troubleshoot this case please do the following:
1. Provide an OS version where you are trying to run Hidden (including its bitness)
2. In a command line please run a command: _sc query hidden_
3. Then try to run again a hiddencli and when it returns an error code run a command: _echo %errorlevel%_, it should display an exact error code.

Regards,
JK

**Comment by JKornev** [comment]
No response, closed
