### ISSUE TITLE
Just curious...

### ISSUE THREAD

**Issue by goraegori** [JKornev/hidden#21]
I just came up with a new thought.
Is file-deceiving possible with driver?
I mean, will it be possible to 
leave the file size, hashes, etc the same as original
and change the file contents to another( by controlling read from another process )
so that I could leave the file unmodified, and modify the content read from it.

eg.)
file.txt : "this is file-content", 5kb, MD5:10001
         Using a driver to make usermode programs think like this:

file.txt : "this is modified-file-content", 5kb, MD5:10001

sorry for hard-to-understands,
do you think it's possible?

**Comment by JKornev** [comment]
Hi,

Sure it's possible, but for hidden I can't see a profit from this feature, could you explain a case when it might be useful?

**Comment by goraegori** [comment]
Sorry for opening an issue here. I wrote it cause I have no one to ask about it and there no e-mail or something. Hope I was not rude. 

Would you mind if you give me some keywords about the feature(function to look for)?

**Comment by JKornev** [comment]
An issue not actual, closed
