### ISSUE TITLE
errors in compile hidden.sys 64bit release 

### ISSUE THREAD

**Issue by ABD-FH** [JKornev/hidden#24]
Hello every one ..
firstly thank you to sharing this service that is has fully features  

i am replyed in last issue about hidden.sys do not working with win 64 bit and the owner is telled us to recompile the driver 64bit release and when i tried i got a lot of errors about transfer from 32bit to 64bit issues EX: Arithmetic overflow: Using operator '+' on a 4 byte value and then casting the result to a 8 byte value. Cast the value to the wider type before calling operator '+' to avoid overflow 

and of course i can't solve it so i can't compile it ..
can you help us to share the driver source code that is work with 64bit if you have the solution for these problems 

thank you..

**Comment by JKornev** [comment]
Hi,

What is your driver build environment? WDK\Vusual Studio version?

I guess this issue happens because the newest compiler has more paranoid settings related to compilation warnings. It's ok if you changed warning level in driver settings. I'll check and fix it soon.

Regards,
JK

**Comment by ABD-FH** [comment]
i am work on visual studio 2019 and WDK-Windows 10.0.18362.1

**Comment by DULI2x** [comment]
> i am work on visual studio 2019 and WDK-Windows 10.0.18362.1

SHARE FILE FOR ME :D thanks

**Comment by JKornev** [comment]
Fixed, @DULI2x just download the latest Windows Driver Kit there is not need a specific version
