### ISSUE TITLE
Any way to forbid create new files in a drive root directory ?

### ISSUE THREAD

**Issue by atmgnd** [JKornev/hidden#25]
Hello, I found this project very usefull, here is what I want to do:
1. Forbid create new files in a drive's root directory, like D:\
2. Hide some files in D:\, like D:\111.txt. but still allow user to read/write to other files in D:\.

any suggestions ? thanks.

**Comment by JKornev** [comment]
Hi,

According to the first question not sure Hidden can prevent an access to D;, you can do it controlling access rights on a D; disk just try to remove right that allows user create new files on disk. Related to a second question you can use hidden and hide files, just install a driver and use hiddencli to hide new files.

JK
