### ISSUE TITLE
a new unresolved external after update visual studio last version   RtlUnicodeStringPrintf

### ISSUE THREAD

**Issue by ABD-FH** [JKornev/hidden#28]
Severity | Code | Description | Project | File | Line | Suppression State
-- | -- | -- | -- | -- | -- | --
Error | LNK2019 | unresolved external symbol __stdio_common_vswprintf referenced in function RtlUnicodeStringPrintf | Hidden | C:\Desktop\hidden-master\hidden-master\Hidden\RegFilter.obj | 1 | &nbsp;

**Comment by ABD-FH** [comment]
please if you find the answer help me ,
in past the driver was compiled good but after update i faced the problem

**Comment by JKornev** [comment]
Hi,

Thanks for your report, I'll check it today

JK.

**Comment by JKornev** [comment]
Hi,

Seems like an issue on your side. Just install the latest version of Windows SDK and Windows Driver Kit and download a project again or revert previous to a initial state. Should work fine just checked.

Regards,
JK
