### ISSUE TITLE
This driver has been blocked from loading!

### ISSUE THREAD

**Issue by mohamadrezashafie** [JKornev/hidden#29]
I get this message when I run "sc start Hidden":

This driver has been blocked from loading

windows10 (ver 2004) wdk10 visual studio 2019
I stop all security tools (windows defender, firewall and I don't have any security software).
Is this message from patch garud?

**Comment by JKornev** [comment]
Seems like an issue has been resolved. So did it happen because you forgot to turn off digital signature enforcement?
