### ISSUE TITLE
Windows 10

### ISSUE THREAD

**Issue by esfomeado** [JKornev/hidden#3]
Unable to compile with windows 10 toolset

**Comment by JKornev** [comment]
Ok I'll check. What exact environment do you use?

**Comment by esfomeado** [comment]
Windows 10 64 bits Anniversary update.
Visual studio 2015

**Comment by JKornev** [comment]
Hi,

It's looks like that you try to build this solution on SDK 10.0, you may try to install WDK 8.1 and build on it.
