### ISSUE TITLE
Windows cannot verify the digital signature for this file

### ISSUE THREAD

**Issue by DULI2x** [JKornev/hidden#30]
bcdedit /enum
[...]
testsigning             Yes
[...]
C:\Windows\system32>sc start hidden
[SC] StartService FAILED 577:
Windows cannot verify the digital signature for this file. A recent hardware or software change might have installed a file that is signed incorrectly or damaged, or that might be malicious software from an unknown source.

C:\Windows\system32>sc query hidden

SERVICE_NAME: hidden
        TYPE               : 2  FILE_SYSTEM_DRIVER
        STATE              : 1  STOPPED
        WIN32_EXIT_CODE    : 577  (0x241)
        SERVICE_EXIT_CODE  : 0  (0x0)
        CHECKPOINT         : 0x0
        WAIT_HINT          : 0x0
This driver has been blocked from loading
How to fix

**Comment by JKornev** [comment]
Hi,

Ok, do you have a kernel debug mode on mixed with testsigning? Try to turn off Microsoft Defender.

Regards,
JK.

**Comment by JKornev** [comment]
Do not forget to build "Hidden Package" but not just "Hidden". Because when you build just a "Hidden" it doesn't sign a driver with a  testing signature. So try to build "Hidden Package" as it explained in a project readme https://github.com/JKornev/hidden#readme

JK.

**Comment by DULI2x** [comment]
I tried everything but not woking

**Comment by DULI2x** [comment]
![image](https://user-images.githubusercontent.com/86325228/124404872-f282e780-dd66-11eb-8f58-92c42899836f.png)
TestSigning has turned on
Microsoft Defender has turned off
Fix for me

**Comment by JKornev** [comment]
If it doesn't help so please attach a driver binary that you are trying to install. I'll check it on my environment.

**Comment by DULI2x** [comment]
I'm using the attached version here
https://github.com/JKornev/hidden/releases/tag/v1.0

**Comment by JKornev** [comment]
Ok I see a repro, I compiled a new version v1.1, so try it and let me know does it solve an issue.

https://github.com/JKornev/hidden/releases/tag/v1.1

**Comment by DULI2x** [comment]
Problem solved, Thank you
