### ISSUE TITLE
Windows cannot verify the digital signature for this file #30

### ISSUE THREAD

**Issue by DULI2x** [JKornev/hidden#31]
bcdedit /enum
[...]
testsigning Yes
[...]
C:\Windows\system32>sc start hidden
[SC] StartService FAILED 577:
Windows cannot verify the digital signature for this file. A recent hardware or software change might have installed a file that is signed incorrectly or damaged, or that might be malicious software from an unknown source.

C:\Windows\system32>sc query hidden

SERVICE_NAME: hidden
TYPE : 2 FILE_SYSTEM_DRIVER
STATE : 1 STOPPED
WIN32_EXIT_CODE : 577 (0x241)
SERVICE_EXIT_CODE : 0 (0x0)
CHECKPOINT : 0x0
WAIT_HINT : 0x0
This driver has been blocked from loading
How to fix

**Comment by JKornev** [comment]
Duplicated https://github.com/JKornev/hidden/issues/30
