### ISSUE TITLE
Typo in function FltDirCtrlPreOperation?

### ISSUE THREAD

**Issue by FlyAs** [JKornev/hidden#32]
Line 155 of source file FsFilter.c:
`return FLT_POSTOP_FINISHED_PROCESSING;`

Should be?:
`return FLT_PREOP_SUCCESS_NO_CALLBACK;`

**Comment by JKornev** [comment]
Hi,

Thanks for the bug-report, fixed.

**Comment by JKornev** [comment]
1e965bbe2d2e42e12d0862250ff12e3f94883440
