### ISSUE TITLE
process hide didn,t work build 1.1 latest

### ISSUE THREAD

**Issue by neamat-ar** [JKornev/hidden#34]
C:\Windows\system32>hiddencli /hide pid 820
Error, invalid argument for command 'hide'
status:failed

**Comment by JKornev** [comment]
Hi,

Correct, 1.1 doesn't have hiding process feature because this is a new feature and it's not completed yet. I'm planning to complete it in a month and make a release 1.2.

For now if you want to use it you have to compile a project by your own.

JK

**Comment by neamat-ar** [comment]
ok
can you please add hide service and hide driver future to this relesase 1.2 
and thanks for this greate tool and your hard works

**Comment by JKornev** [comment]
I've planned to implement stuff you mentioned but this is not going to be ready in 1.2 for sure

JK

**Comment by iamtrying-127times** [comment]
Hi.
Can you compile it?
I've tried, but failed multiple attempts, each one with a different error.
Thanks
