### ISSUE TITLE
Driver has been blocked from loading Error

### ISSUE THREAD

**Issue by ameygat** [JKornev/hidden#36]
VM OS: Windows 10 64 Bit. No service pack
Driver file: Uploaded in comment bellow

Before install I have done following commands

`bcdedit /set loadoptions DDISABLE_INTEGRITY_CHECKS & bcdedit /set testsigning on`

I have also installed the .CER certificate in the release folder in the windows.

Also disabled the WIndows Defender from VM

Then rebooted VM then tried installing driver using following command:

```
Microsoft PnP Utility

Processing inf :            Hidden.inf
Successfully installed the driver.
Driver package added successfully.
Published name :            oem11.inf


Total attempted:              1
Number successfully imported: 1
```

But when I tried to start service get error:

```
cmd>sc start hidden
[SC] StartService FAILED 1275:

This driver has been blocked from loading


```

Note: First I had tried just right click and install driver but it also failed to start service saying "This driver has been blocked from loading"

Any help or pointers appreciated.

**Comment by ameygat** [comment]
Uploading failed driver files
[Release.zip](https://github.com/JKornev/hidden/files/8537530/Release.zip)

**Comment by ameygat** [comment]
Sorry it was issue on my end it was 32 bit compile.

**Comment by JKornev** [comment]
Not a problem
