### ISSUE TITLE
Compiling on windows 10

### ISSUE THREAD

**Issue by matteke-games** [JKornev/hidden#5]
Hi,
First, that is an awesome project! But I'm not able to compile it, neither on sdk 8.1 nor 10, when compiling it gives the following error(s) unresolved external symbol FltRegisterFilter referenced in function InitializeFSMiniFilter in FsFilter.c, I make a new issue because it does not seem related to one of the other (closed) issues and was hoping that you could help me with it. Thanks(sidenote, I made no changes to the code, the code I try to compile is exactly the same as currently in the master branch)

**Comment by JKornev** [comment]
Hi,

Could you please copy full output during compiling. FltRegisterFilter is a part of WDK but unsolved external symbol means that you have compiled a code and linker can''t find lib with FltRegisterFilter. Hm...

**Comment by matteke-games** [comment]
The output:
1>------ Build started: Project: Hidden, Configuration: Debug Win32 ------
1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(724,5): error : The OutputPath property is not set for project 'Hidden.vcxproj'.  Please check to make sure that you have specified a valid combination of Configuration and Platform for this project.  Configuration='Debug'  Platform='Win32'.  This error may also appear if some other project is trying to follow a project-to-project reference to this project, this project has been unloaded or is not included in the solution, and the referencing project does not build using the same or an equivalent Configuration or Platform.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
========== Deploy: 0 succeeded, 0 failed, 0 skipped ==========
Now I get this, but if I add your code to a new project, it gives:

1>------ Build started: Project: TEST, Configuration: Debug x64 ------
1>  Building 'TEST' with toolset 'WindowsKernelModeDriver10.0' and the 'Universal' target platform.
1>  Stamping x64\Debug\TEST.inf [Version] section with DriverVer=05/31/2017,8.48.58.578
1>FsFilter.obj : error LNK2019: unresolved external symbol FltRegisterFilter referenced in function InitializeFSMiniFilter
1>FsFilter.obj : error LNK2019: unresolved external symbol FltUnregisterFilter referenced in function DestroyFSMiniFilter
1>FsFilter.obj : error LNK2019: unresolved external symbol FltStartFiltering referenced in function InitializeFSMiniFilter
1>FsFilter.obj : error LNK2019: unresolved external symbol FltGetFileNameInformation referenced in function FltCreatePreOperation
1>FsFilter.obj : error LNK2019: unresolved external symbol FltReleaseFileNameInformation referenced in function FltCreatePreOperation
1>C:\Users\unnamed\documents\visual studio 2015\Projects\TEST\x64\Debug\TEST.sys : fatal error LNK1120: 5 unresolved externals
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by JKornev** [comment]
So look, I pushed a commit 8e2e30d that contains some changes on project settings (just cleanup), try it. If it doesn't solve your issue please make sure that you are trying to build on Release or Debug configurations and with platform Win32 or x64 (not Mixed, Any CPU and etc). If it doesn't solve your issue again try to modify Hidden.vcxproj as it is described on the following link: https://stackoverflow.com/questions/15134384/the-outputpath-property-is-not-set-for-project. Waiting for your response.

**Comment by JKornev** [comment]
Ok, I have closed this issue, you may create a new one if the instructions above don't help you
