### ISSUE TITLE
Keep getting unknown perform mode, please use hidencli /help

### ISSUE THREAD

**Issue by dasneko** [JKornev/hidden#6]
C:\Users\Hephaetus\Desktop\HideDriver_bin\hidden-master\x64\Debug>HiddenCLI
Welcome to HiddenCLI, please use 'hiddencli /help'
status:failed

C:\Users\Hephaetus\Desktop\HideDriver_bin\hidden-master\x64\Debug>HiddenCLI install
Error, unknown command, please use 'hiddencli /help'
status:failed

C:\Users\Hephaetus\Desktop\HideDriver_bin\hidden-master\x64\Debug>HiddenCLI /install
Error, unknown perform mode, please use 'hiddencli /help'
status:failed

C:\Users\Hephaetus\Desktop\HideDriver_bin\hidden-master\x64\Debug>HiddenCLI /install me
Error, unknown perform mode, please use 'hiddencli /help'
status:failed

C:\Users\Hephaetus\Desktop\HideDriver_bin\hidden-master\x64\Debug>HiddenCLI
Welcome to HiddenCLI, please use 'hiddencli /help'
status:failed

C:\Users\Hephaetus\Desktop\HideDriver_bin\hidden-master\x64\Debug>HiddenCLI
Welcome to HiddenCLI, please use 'hiddencli /help'
status:failed

C:\Users\Hephaetus\Desktop\HideDriver_bin\hidden-master\x64\Debug>HiddenCLI /INSTALL
Error, unknown command, please use 'hiddencli /help'
status:failed

C:\Users\Hephaetus\Desktop\HideDriver_bin\hidden-master\x64\Debug>HiddenCLI state on
Error, unknown command, please use 'hiddencli /help'
status:failed

C:\Users\Hephaetus\Desktop\HideDriver_bin\hidden-master\x64\Debug>HiddenCLI /state
Error, mismatched argument #1 for command 'state'
status:failed

C:\Users\Hephaetus\Desktop\HideDriver_bin\hidden-master\x64\Debug>HiddenCLI /state on
Error, can't connect to gate
status:failed

C:\Users\Hephaetus\Desktop\HideDriver_bin\hidden-master\x64\Debug>HiddenCLI /gate HiddenGate
Error, unknown perform mode, please use 'hiddencli /help'
status:failed

C:\Users\Hephaetus\Desktop\HideDriver_bin\hidden-master\x64\Debug>HiddenCLI /gate Hweeeeeeeeeee
Error, unknown perform mode, please use 'hiddencli /help'
status:failed

C:\Users\Hephaetus\Desktop\HideDriver_bin\hidden-master\x64\Debug>HiddenCLI gate we
Error, unknown command, please use 'hiddencli /help'
status:failed

C:\Users\Hephaetus\Desktop\HideDriver_bin\hidden-master\x64\Debug>HiddenCLI /gate XXXXA
Error, unknown perform mode, please use 'hiddencli /help'
status:failed

**Comment by JKornev** [comment]
Hi dasneko,

What are you going to perform? Please use "hiddencli /help" to read usage. Command /install means that you are going to put commands to registry key and driver will load them automatically on start. For instance:
`hiddencli /install /hide file c:\file_to_hide.txt`
This command should install this command for a driver in registry, and when you start a driver it will perform it.

`C:\Users\Hephaetus\Desktop\HideDriver_bin\hidden-master\x64\Debug>HiddenCLI /state on
Error, can't connect to gate
status:failed`
According to this error, did you install the driver? And did you run it?

**Comment by JKornev** [comment]
No response from topic starter, therefore closed

**Comment by GhostNaix** [comment]
Seems like he didn't load the driver into the kernel
