### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by w3sh** [JKornev/hidden#8]
please add this code in .Net Platform: VBnet, C#

**Comment by JKornev** [comment]
Hi,

I'm not sure that I'm going to do that. But there is a HiddenLib and you may just compile it as a DLL and then load it to .NET application. So all in your hands :) can't see a problem here.

Closed

**Comment by JKornev** [comment]
FYI, HiddenLib it's a library that allows you to communicate with a driver
